#!/bin/bash
scriptPath=$(pwd)
pathToRealAutoGTP=~/git/leela-zero/autogtp
pipe=$scriptPath/$(od -A n -t x -N 4 /dev/urandom | tr -d [:space:]).tmpPipe

#make pipe which does not clash with other instances of LeelaWatcher
while [ -e $pipe ]
do
  pipe=$scriptPath/$(od -A n -t x -N 4 /dev/urandom | tr -d [:space:]).tmpPipe
done
mkfifo $pipe

#fork and disown process so it will survive longer than this process
cd $pathToRealAutoGTP
$scriptPath/waitToSendQ.sh $$ $pipe | nice -n 42 $pathToRealAutoGTP/autogtp -w -k finishedGames $@ >$pipe & disown

#forward output
cat $pipe </dev/null

