/*
    Copyright 2017 Patrick G. Heck

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 */
package tsb.gui;

/*
 * FeatureNotSupDlg.java
 *
 * Created on October 4, 2001, 11:45 AM
 */


import java.awt.*;

/**
 * @author Patrick G. Heck
 */
public class IntroDlg extends javax.swing.JDialog {

  /**
   * Creates new form FeatureNotSupDlg
   */
  public IntroDlg(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();

    Dimension dm;
    Toolkit tk = Toolkit.getDefaultToolkit();
    dm = tk.getScreenSize();

    pack();
    setSize(280, 100);
    setLocation(dm.width / 2 - 140, dm.height / 2 - 50);
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    jLabel1 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jButton3 = new javax.swing.JButton();
    getContentPane().setLayout(new java.awt.FlowLayout());
    setName("Feature Not Supported");
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowClosing(java.awt.event.WindowEvent evt) {
                          closeDialog(evt);
                        }
                      }
    );

    jLabel1.setText("Please read \"About\" in the Help Menu.");


    getContentPane().add(jLabel1);

    jPanel1.setPreferredSize(new java.awt.Dimension(120, 45));

    jButton3.setText("OK");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                   jButton3ActionPerformed(evt);
                                 }
                               }
    );

    jPanel1.add(jButton3);


    getContentPane().add(jPanel1);

  }//GEN-END:initComponents

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// Add your handling code here:
    java.awt.event.WindowEvent closeDlg
        = new java.awt.event.WindowEvent(this, java.awt.event.WindowEvent.WINDOW_CLOSING);
    closeDialog(closeDlg);
  }//GEN-LAST:event_jButton3ActionPerformed

  /**
   * Closes the dialog
   */
  private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
    setVisible(false);
    dispose();
  }//GEN-LAST:event_closeDialog

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    new IntroDlg(new javax.swing.JFrame(), true).show();
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton jButton3;
  // End of variables declaration//GEN-END:variables

}